app:
  id: mymdw61

container:
  datasource.provider: Tomcat
  messenger: jms
  jms.provider: ActiveMQ
  threadpool.provider: MDW

database:
  driver: org.mariadb.jdbc.Driver
  url: jdbc:mariadb://localhost:3308/mdw
  username: mdw
  password: mdw
  poolsize: 5
  poolMaxIdle: 3
  validationQuery: select 1 from dual

# optional mongodb
# mongodb:
#   host: localhost
#   port: 27017

# asset location info (use absolute paths when running thru eclipse wtp) 
asset:
  location: C:/mdw/mymdw61/assets

git:
  local.path: C:/mdw/mymdw61
  remote.url: https://github.com/joelitoom/mdw-test.git
  branch: master

temp.dir: assets/../temp

hub.url: http://localhost:8080/mdw
services.url: http://localhost:8080/mdw
discovery.url: http://repo.maven.apache.org/maven2
central.url: https://mdw.useast.appfog.ctl.io/mdw

logging:
  level: DEBUG

mail:
  smtp.host: mymailhost
  smtp.port: 25
  connection.timeout: 10000
  smtp.timeout: 10000

ldap:
  host: ldap.myorg.com
  port: 1636
  base.dn: dc=ad,dc=intra,dc=com

servers:
  localhost:
    ports:
    - 8080
    
# Custom JWT Provider    
#  jwt.custom:
#    issuer: cxg7i.test.intranet
#    userClaim: userid
#    key:

# timer.task:
#   ProcessCleanup: # run daily at 2:30 am
#     TimerClass: com.centurylink.mdw.timer.cleanup.ProcessCleanup
#     Schedule: 30 2 * * ? *
#     RuntimeCleanupScript: Cleanup-Runtime.sql
#     ProcessExpirationAgeInDays: 180
#     ExternalEventExpirationAgeInDays: 180
#     MaximumProcessExpiration: 10000
#     CommitInterval: 10000
